# Generated by Django 3.2.10 on 2022-04-12 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_dummy'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_name',
            field=models.CharField(default=1, max_length=70),
            preserve_default=False,
        ),
    ]
